export const REAL_MADRID = [
  {
    ref: "Lunin",
    name: "Lunin",
    number: 13,
    position: { x: 238, y: 541 },
    moved: false,
  },
  {
    ref: "Carvajal",
    name: "Carvajal",
    number: 2,
    position: { x: 436, y: 429 },
    moved: false,
  },
  {
    ref: "Militao",
    name: "Militao",
    number: 3,
    position: { x: 319, y: 468 },
    moved: false,
  },
  {
    ref: "Alaba",
    name: "Alaba",
    number: 4,
    position: { x: 167, y: 468 },
    moved: false,
  },
  {
    ref: "Fran-Garcia",
    name: "Fran Garcia",
    number: 20,
    position: { x: 35, y: 434 },
    moved: false,
  },
  {
    ref: "Tchouameni",
    name: "Tchouameni",
    number: 18,
    position: { x: 243, y: 351 },
    moved: false,
  },
  {
    ref: "Kross",
    name: "Kross",
    number: 8,
    position: { x: 90, y: 288 },
    moved: false,
  },
  {
    ref: "Valverde",
    name: "Valverde",
    number: 15,
    position: { x: 369, y: 269 },
    moved: false,
  },
  {
    ref: "Belligham",
    name: "Belligham",
    number: 5,
    position: { x: 235, y: 187 },
    moved: false,
  },
  {
    ref: "Vinicius-JR",
    name: "Vinicius JR",
    number: 7,
    position: { x: 162, y: 116 },
    moved: false,
  },
  {
    ref: "Rodrygo",
    name: "Rodrygo",
    number: 11,
    position: { x: 311, y: 116 },
    moved: false,
  },
];
